import = ["~/.config/alacritty/machine-specific-config.toml"]
live_config_reload = true

[colors.bright]
black = "#575b70"
blue = "#7eaef1"
cyan = "#6cdada"
green = "#a8ca23"
magenta = "#ff99ff"
red = "#ff8785"
white = "#e6e6e6"
yellow = "#ffff00"

[colors.normal]
black = "#ffffff"
blue = "#5394ec"
cyan = "#299999"
green = "#a8c023"
magenta = "#ae8abe"
red = "#ff6b68"
white = "#1f1f1f"
yellow = "#d6bf55"

[colors.primary]
background = "#2b2b2b"
foreground = "#bbbbbb"

[font.bold]
style = "Regular"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
decorations = "none"
